# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df15a53133076af5e9b853d4937803afaf0e19016dd6a9609940e98ad2888fb9d98f1735df485f8c3adbeab16978cdab06754cff1e60d3cf80a34b3f38f236d2

test:
  secret_key_base: 42bdef91e44feafb26180c5b9a789ac2ca36e4d6516284dadc300dadb30ba1e5697c5d2a89bb3f7327454713d110fd002759d3784dd21c7977516540cb1f15f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
